from amazoncorretto:11
copy target/dis-0.0.1-SNAPSHOT.jar dis-0.0.1-SNAPSHOT.jar
run mkdir -p src/main/resources/
copy src/main/resources/anime.json src/main/resources/anime.json
cmd ["java", "-jar", "/dis-0.0.1-SNAPSHOT.jar"]